#!/bin/bash

# Nerd Font icons
export ICON_APPLE=""
export ICON_CLOCK=""
export ICON_CALENDAR=""
export ICON_WIFI=""
export ICON_WIFI_OFF="󰤭"
export ICON_VOLUME_HIGH="󰕾"
export ICON_VOLUME_MED="󰖀"
export ICON_VOLUME_LOW="󰕿"
export ICON_VOLUME_MUTE="󰝟"
export ICON_BATTERY_100="󰁹"
export ICON_BATTERY_75="󰂁"
export ICON_BATTERY_50="󰁾"
export ICON_BATTERY_25="󰁻"
export ICON_BATTERY_0="󰂎"
export ICON_BATTERY_CHARGING="󰂄"
export ICON_CPU="󰻠"
export ICON_MEMORY="󰍛"
export ICON_MEDIA="󰎈"
export ICON_MEDIA_PAUSE="󰏤"
